name: 🐛 Bug Report
description: Create a report to help to improve the prettier configuration
title: "bug: "
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please ensure you have completed all of the following.
      options:
        - label: I have searched for [existing issues](https://github.com/boehringer-ingelheim/prettier-config/issues) that already report this problem, without success.
          required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A clear description of what the bug is and how it manifests.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Please explain the steps required to duplicate this issue.
    validations:
      required: true
  - type: input
    attributes:
      label: Code Reproduction URL
      description: Please reproduce this issue and provide a link to the repo. This is the best way to ensure this issue is triaged quickly. Issues without a code reproduction may be closed if the issue cannot be reproduced you are reporting.
      placeholder: https://github.com/...
  - type: textarea
    attributes:
      label: Additional Information
      description: List any other information that is relevant to you
