name: Release

on:
  push:
    branches:
      - main
jobs:
  release:
    env:
      # Disable husky (git hooks) in CI, see: https://typicode.github.io/husky/#/?id=disable-husky-in-cidocker
      HUSKY: 0
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
      - name: Release package to npm and GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release:ci
